grpc:
  enableReflection: true
  port: 9000

sendgrid:
  api-key: enter the key

admin:
  emailId: punitgurnani8@gmail.com

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: nuclei@08@04@2001
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  cache:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: mail
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.subscriptionmanager.kafka.deserializer.NewsletterMailInfoDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.subscriptionmanager.kafka.serializer.NewsletterMailInfoSerializer
    topic:
      name: Newsletter_Mail_Info